feat(styling) : [0001] css styling modification
sandhrarahardjo/first-react-project pull request #1
Opened 2023-05-26 08:25 UTC by sandhrarahardjo

**What problem does this PR solve?**
The lack of styling on the page

**How does this PR solve it?**
Adding columns and background colours 

**Screenshots :**
![Screenshot (109)](https://github.com/sandhrarahardjo/first-react-project/assets/115931684/bcc893d0-1d7b-4fc3-97ef-dca4bf9f5350)

2023-05-26 08:26 UTC, andreantaufik requested changes
minor review

2023-05-26 08:26 UTC, andreantaufik commented on src/index.js
>  const root = ReactDOM.createRoot(document.getElementById('root'));
add new line after import.

2023-05-26 08:28 UTC, andreantaufik commented
// import from external source
import React from 'react';
import ReactDOM from 'react-dom/client';

// local source
import App from './App';
import reportWebVitals from './reportWebVitals';
import './App.css';

// codee

2023-05-26 08:47 UTC, sandhrarahardjo commented
fix(minor changes) : [0001] minor import order fixed

**What problem does this PR solve?**
Import order of the code

**How does this PR solve it?**
Fixed the import order of the code

**Screenshot : **
![Screenshot (111)](https://github.com/sandhrarahardjo/first-react-project/assets/115931684/0954f553-4fc0-4ebf-a84e-73d9decda35d)

2023-05-29 04:02 UTC, andreantaufik approved these changes

2023-05-29 04:28 UTC, merged